project_id: 2352479983        # your Todoist project
max_tasks_per_day: 10         # cap how many new tasks per day
schedule_horizon_days: 7      # look this many days ahead

timezone: America/Toronto     # your IANA timezone

work_hours:                   # only schedule within these hours
  start: "09:00"
  end:   "17:00"

buffer_minutes: 5                     # gap (in minutes) between back‑to‑back tasks
priority_decay_per_day: 1             # how much priority to subtract per day old
default_task_duration_minutes: 15     # fallback task length when AI omits it