name: Daily Todoist AI Scheduler

on:
  schedule:
    # Runs daily at 09:00 UTC (05:00 America/Toronto during EDT)
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  trigger-render:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up the Render scheduler
        run: |
          http_code=$(curl -fsS -o /dev/null -w "%{http_code}" https://todoist-ai-assistant.onrender.com/run)
          echo "Render /run returned HTTP $http_code"